federation_version: 2
subgraphs:
    book:
        routing_url: http://localhost:8081
        schema:
            subgraph_url: http://localhost:8081
    author:
        routing_url: http://localhost:8082
        schema:
            subgraph_url: http://localhost:8082
